server:
  port: 8086

spring:
  datasource:
    url: jdbc:${TYPE}://${HOST}:${PORT}/${NAME}
    username: ${USER}
    password: ${PASSWORD}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: 'smtp.gmail.com'
    username: ${TODO-EMAIL}
    password: ${EMAIL-CODE}
    port: '587'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
