server:
  port: 8086

spring:
  datasource:
    url: jdbc:${TYPE}://${HOST}:${PORT}/${NAME}
    username: ${USER}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
