name: Build and Test

on:
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'BE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test
