name: Build and Test

on:
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'BE/toDoListAPI/**'  # This should match the path to your Maven project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Change directory to the project root
        run: cd BE/toDoListAPI

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Run tests
        run: mvn test
